### ISSUE TITLE
Link Outdated

### ISSUE THREAD

**Issue by triggerman86** [glallen01/csirt-essential-reading#2]
@sroberts Introduction to DFIR

404 Error

**Comment by triggerman86** [comment]
Updated Link:
https://medium.com/@sroberts/introduction-to-dfir-d35d5de4c180

**Comment by sroberts** [comment]
@dtmarr Thanks for noticing! Yeah I moved over to Medium and sorta messed these things up. My bad!

**Comment by glallen01** [comment]
Fixed
